export const scrambleWords = [
  // Easy (3-6 letters)
  { scrambled: 'hte', answer: 'ETH' },
  { scrambled: 'ncoi', answer: 'COIN' },
  { scrambled: 'nteko', answer: 'TOKEN' },
  { scrambled: 'klcob', answer: 'BLOCK' },
  { scrambled: 'nhaci', answer: 'CHAIN' },
  { scrambled: 'llawet', answer: 'WALLET' },
  { scrambled: 'pyrtc', answer: 'CRYPT' },
  { scrambled: 'nirem', answer: 'MINER' },
  { scrambled: 'sga', answer: 'GAS' },
  { scrambled: 'deno', answer: 'NODE' },
  { scrambled: 'lhod', answer: 'HODL' },
  { scrambled: 'ppad', answer: 'DAPP' },
  { scrambled: 'tfn', answer: 'NFT' },
  { scrambled: 'ofom', answer: 'FOMO' },

  // Medium (6-9 letters)
  { scrambled: 'gredel', answer: 'LEDGER' },
  { scrambled: 'prodria', answer: 'AIRDROP' },
  { scrambled: 'gantkis', answer: 'STAKING' },
  { scrambled: 'canorttc', answer: 'CONTRACT' },
  { scrambled: 'forpo', answer: 'PROOF' },
  { scrambled: 'diley', answer: 'YIELD' },
  { scrambled: 'qiludi', answer: 'LIQUID' },
  { scrambled: 'kortwne', answer: 'NETWORK' },
  { scrambled: 'lacneab', answer: 'BALANCE' },
  { scrambled: 'gdebir', answer: 'BRIDGE' },
  { scrambled: 'oitsahs', answer: 'SATOSHI' },
  { scrambled: 'imawg', answer: 'WAGMI' },
  { scrambled: 'gende', answer: 'DEGEN' },
  { scrambled: 'emocmine', answer: 'MEMECOIN' },

  // Hard (8-12+ letters)
  { scrambled: 'skaatemm', answer: 'METAMASK' },
  { scrambled: 'cabhinkolc', answer: 'BLOCKCHAIN' },
  { scrambled: 'martscantorc', answer: 'SMARTCONTRACT' },
  { scrambled: 'traliendecedz', answer: 'DECENTRALIZED' },
  { scrambled: 'davilator', answer: 'VALIDATOR' },
  { scrambled: 'sensusnoc', answer: 'CONSENSUS' },
  { scrambled: 'santorinact', answer: 'TRANSACTION' },
  { scrambled: 'comiketoson', answer: 'TOKENOMICS' },
  { scrambled: 'lumgisti', answer: 'MULTISIG' },
  { scrambled: 'torenipearebl', answer: 'INTEROPERABLE' },
];